/**
 * Minimal JSON key-value store
 *
 * Used to persist user accounts and short subscription links. Backed by
 * Vercel Blob **private** blobs, so records are only readable with the
 * store's read-write token (never through a public URL).
 *
 * Keeping this behind a small interface makes it easy to plug in another
 * backend (Redis/KV/D1/...) later without touching the API routes.
 */

import { put, get, del } from '@vercel/blob';

export interface KVStore {
  /** Human readable provider identifier (e.g. "vercel-blob") */
  readonly name: string;

  /** Whether the provider is configured and ready to use */
  isConfigured(): boolean;

  /** Read a JSON record, or null when the key does not exist */
  read<T>(key: string): Promise<T | null>;

  /** Write a JSON record */
  write<T>(key: string, value: T): Promise<void>;

  /** Remove a record; missing keys are ignored */
  remove(key: string): Promise<void>;
}

/**
 * Vercel Blob backed KV store.
 *
 * Records live under `data/<key>.json` as private blobs. Reads bypass the
 * CDN cache so a rotated token takes effect immediately.
 */
export class VercelBlobKV implements KVStore {
  readonly name = 'vercel-blob';

  isConfigured(): boolean {
    return Boolean(process.env.BLOB_READ_WRITE_TOKEN);
  }

  private pathname(key: string): string {
    // Keys are generated by this app (`user:<name>`, `link:<id>`) and are
    // already restricted to safe characters, but normalize defensively.
    const safe = key.replace(/:/g, '/').replace(/[^a-zA-Z0-9/._-]/g, '_');
    return `data/${safe}.json`;
  }

  private assertConfigured(): void {
    if (!this.isConfigured()) {
      throw new Error(
        'Storage is not configured. Connect a Vercel Blob store and set the ' +
          'BLOB_READ_WRITE_TOKEN environment variable.'
      );
    }
  }

  async read<T>(key: string): Promise<T | null> {
    this.assertConfigured();

    const result = await get(this.pathname(key), {
      access: 'private',
      // Always read the freshest copy: tokens and mappings change often.
      useCache: false,
    });

    if (!result || result.statusCode !== 200) {
      return null;
    }

    const text = await new Response(result.stream).text();
    if (!text.trim()) {
      return null;
    }

    try {
      return JSON.parse(text) as T;
    } catch {
      throw new Error(`Corrupted record for key: ${key}`);
    }
  }

  async write<T>(key: string, value: T): Promise<void> {
    this.assertConfigured();

    await put(this.pathname(key), JSON.stringify(value), {
      access: 'private',
      addRandomSuffix: false,
      allowOverwrite: true,
      contentType: 'application/json',
      // Minimum accepted by Vercel Blob; reads bypass the cache anyway.
      cacheControlMaxAge: 60,
    });
  }

  async remove(key: string): Promise<void> {
    this.assertConfigured();

    try {
      await del(this.pathname(key));
    } catch (error) {
      // Deleting a missing record is not an error.
      if (error instanceof Error && error.name === 'BlobNotFoundError') return;
      throw error;
    }
  }
}

let cachedStore: KVStore | null = null;

/** Get the configured KV store (currently Vercel Blob only) */
export function getKVStore(): KVStore {
  if (!cachedStore) {
    cachedStore = new VercelBlobKV();
  }
  return cachedStore;
}
